<?php

namespace App\Services;

use App\Models\Categoria;
use App\Models\Producto;
use App\Models\ProductoImagen;
use App\Models\SyncLog;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use JsonException;
use Throwable;

class YupooImporter
{
    /**
     * Sync a single album record immediately.
     */
    public function syncRecord(array $record): array
    {
        return $this->syncProduct($record);
    }

    /**
     * Import the JSON generated by the Playwright scraper into MySQL.
     */
    public function import(string $jsonPath): array
    {
        if (! File::exists($jsonPath)) {
            throw new \RuntimeException("No se encontro el archivo JSON: {$jsonPath}");
        }

        $log = SyncLog::create([
            'started_at' => now(),
            'status' => 'importing',
            'meta' => [
                'json_path' => $jsonPath,
                'source' => 'playwright',
            ],
        ]);

        $summary = [
            'records' => 0,
            'products_created' => 0,
            'products_updated' => 0,
            'categories_created' => 0,
            'images_synced' => 0,
            'errors' => [],
        ];

        try {
            $payload = $this->decodeJson(File::get($jsonPath));

            foreach ($payload as $record) {
                try {
                    $result = $this->syncProduct($record);
                    $summary['records']++;
                    $summary['products_created'] += $result['created'];
                    $summary['products_updated'] += $result['updated'];
                    $summary['categories_created'] += $result['categories'];
                    $summary['images_synced'] += $result['images'];
                } catch (Throwable $exception) {
                    $summary['errors'][] = $this->recordLabel($record).': '.$exception->getMessage();
                }
            }

            $log->update([
                'finished_at' => now(),
                'status' => empty($summary['errors']) ? 'finished' : 'finished_with_errors',
                'albums_found' => $summary['records'],
                'products_created' => $summary['products_created'],
                'products_updated' => $summary['products_updated'],
                'images_synced' => $summary['images_synced'],
                'errors_count' => count($summary['errors']),
                'summary' => $this->summaryText($summary),
                'meta' => array_merge($log->meta ?? [], [
                    'categories_created' => $summary['categories_created'],
                    'errors' => $summary['errors'],
                ]),
            ]);
        } catch (Throwable $exception) {
            $log->update([
                'finished_at' => now(),
                'status' => 'failed',
                'errors_count' => 1,
                'summary' => $exception->getMessage(),
                'meta' => array_merge($log->meta ?? [], [
                    'exception' => $exception::class,
                ]),
            ]);

            throw $exception;
        }

        return [
            'log' => $log->fresh(),
            'summary' => $summary,
        ];
    }

    /**
     * Decode the JSON payload and validate basic structure.
     */
    private function decodeJson(string $json): array
    {
        try {
            $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new \RuntimeException('El JSON generado por el scraper no es valido: '.$exception->getMessage(), previous: $exception);
        }

        if (! is_array($decoded)) {
            throw new \RuntimeException('El JSON generado por el scraper no tiene el formato esperado.');
        }

        return $decoded;
    }

    /**
     * Sync a single album record into categorias, productos and producto_imagenes.
     */
    private function syncProduct(array $record): array
    {
        return DB::transaction(function () use ($record) {
            $albumId = (string) ($record['album_id'] ?? '');
            $tituloOriginal = trim((string) ($record['titulo'] ?? ''));
            $url = trim((string) ($record['url'] ?? ''));
            $categoriaName = 'Retos';
            $portada = $this->normalizeUrl($record['portada'] ?? null);
            $imagenes = $this->normalizeImageList($record['imagenes'] ?? []);

            if ($albumId === '' || $url === '') {
                throw new \RuntimeException('Registro incompleto: album_id, titulo y url son obligatorios.');
            }

            $titulo = $this->spanishTitle($albumId, $tituloOriginal);

            $categoria = null;
            $categoriesCreated = 0;

            $categoriaSlug = $this->uniqueCategorySlug($categoriaName);
            $categoria = Categoria::query()->firstOrCreate(
                ['slug' => $categoriaSlug],
                [
                    'titulo' => $categoriaName,
                    'yupoo_url' => null,
                ]
            );

            $categoriesCreated = $categoria->wasRecentlyCreated ? 1 : 0;

            $producto = Producto::query()->where('yupoo_album_id', $albumId)->first();
            $isNew = $producto === null;

            if ($producto === null) {
                $producto = new Producto();
                $producto->slug = $this->uniqueProductSlug($titulo, $albumId);
            }

            $producto->fill([
                'categoria_id' => $categoria?->id,
                'yupoo_album_id' => $albumId,
                'titulo' => $titulo,
                'portada_url' => $portada ?: ($imagenes[0] ?? null),
                'yupoo_url' => $url,
                'descripcion' => $tituloOriginal !== '' ? $tituloOriginal : null,
            ]);

            $producto->save();

            $imagesSynced = $this->syncImages($producto, $imagenes, $portada ?: ($imagenes[0] ?? null), $titulo);

            return [
                'created' => $isNew ? 1 : 0,
                'updated' => $isNew ? 0 : 1,
                'categories' => $categoriesCreated,
                'images' => $imagesSynced,
            ];
        });
    }

    /**
     * Replace album images with the fresh URLs from the scraper.
     */
    private function syncImages(Producto $producto, array $imagenes, ?string $portada, string $titulo): int
    {
        $finalImages = [];
        $seen = [];

        foreach ($imagenes as $imageUrl) {
            $normalized = $this->normalizeUrl($imageUrl);

            if ($normalized === null || ! $this->isAllowedImageUrl($normalized)) {
                continue;
            }

            if (! isset($seen[$normalized])) {
                $seen[$normalized] = true;
                $finalImages[] = $normalized;
            }
        }

        if ($portada !== null && $this->isAllowedImageUrl($portada) && ! isset($seen[$portada])) {
            array_unshift($finalImages, $portada);
        }

        $existing = $producto->imagenes()->orderBy('orden')->pluck('url')->all();

        if ($existing !== $finalImages) {
            $producto->imagenes()->delete();

            foreach ($finalImages as $index => $url) {
                ProductoImagen::create([
                    'producto_id' => $producto->id,
                    'url' => $url,
                    'orden' => $index,
                    'alt' => $titulo.' '.($index + 1),
                ]);
            }
        }

        return count($finalImages);
    }

    /**
     * Normalize image URLs and discard invalid values.
     */
    private function normalizeImageList(array $images): array
    {
        $urls = [];
        $seenFolders = [];

        foreach ($images as $image) {
            $normalized = $this->normalizeUrl($image);

            if ($normalized !== null && $this->isAllowedImageUrl($normalized) && $this->keepBestVariant($normalized, $seenFolders) && ! in_array($normalized, $urls, true)) {
                $urls[] = $normalized;
            }
        }

        return $urls;
    }

    /**
     * Keep one image per folder and prefer non-variant filenames.
     */
    private function keepBestVariant(string $url, array &$seenFolders): bool
    {
        $parts = parse_url($url);

        if (! isset($parts['path'])) {
            return false;
        }

        $segments = array_values(array_filter(explode('/', $parts['path'])));
        $folderKey = implode('/', array_slice($segments, 0, -1));
        $fileName = strtolower(end($segments) ?: '');
        $isVariant = (bool) preg_match('/^(big|small|mid|thumb|large)\.jpg$/i', $fileName);

        if (! isset($seenFolders[$folderKey])) {
            $seenFolders[$folderKey] = [
                'url' => $url,
                'variant' => $isVariant,
            ];

            return true;
        }

        $current = $seenFolders[$folderKey];

        if ($current['variant'] && ! $isVariant) {
            $seenFolders[$folderKey] = [
                'url' => $url,
                'variant' => false,
            ];

            return true;
        }

        return false;
    }

    /**
     * Normalize Yupoo image URLs.
     */
    private function normalizeUrl(mixed $value): ?string
    {
        if (! is_string($value)) {
            return null;
        }

        $value = html_entity_decode(trim($value), ENT_QUOTES | ENT_HTML5, 'UTF-8');

        if ($value === '' || str_starts_with($value, 'data:')) {
            return null;
        }

        if (str_starts_with($value, '/storage/')) {
            return $value;
        }

        if (str_starts_with($value, 'storage/')) {
            return '/'.ltrim($value, '/');
        }

        if (str_starts_with($value, '//')) {
            $value = 'https:'.$value;
        } elseif (str_starts_with($value, '/')) {
            $value = 'https://classic-football-fhirts052.x.yupoo.com'.$value;
        } elseif (! str_starts_with($value, 'http://') && ! str_starts_with($value, 'https://')) {
            $value = 'https://classic-football-fhirts052.x.yupoo.com/'.ltrim($value, '/');
        }

        $value = preg_replace('/([?&#].*)$/', '', $value) ?? $value;

        if (str_starts_with($value, 'http://')) {
            $value = 'https://'.substr($value, 7);
        }

        $value = $this->canonicalizePhotoUrl($value);

        return filter_var($value, FILTER_VALIDATE_URL) ? $value : null;
    }

    /**
     * Canonicalize Yupoo photo variants to the big image URL.
     */
    private function canonicalizePhotoUrl(string $url): string
    {
        $parts = parse_url($url);

        if (! isset($parts['scheme'], $parts['host'], $parts['path'])) {
            return $url;
        }

        if ($parts['host'] !== 'photo.yupoo.com') {
            return $url;
        }

        $segments = array_values(array_filter(explode('/', $parts['path'])));

        if (count($segments) >= 2) {
            $last = strtolower($segments[count($segments) - 1]);

            if (in_array($last, ['big.jpg', 'small.jpg', 'mid.jpg', 'thumb.jpg', 'large.jpg'], true)) {
                $segments[count($segments) - 1] = 'big.jpg';
                $parts['path'] = '/'.implode('/', $segments);

                return $this->buildUrl($parts);
            }
        }

        return $url;
    }

    /**
     * Rebuild a URL from parsed components.
     */
    private function buildUrl(array $parts): string
    {
        $url = $parts['scheme'].'://'.$parts['host'];

        if (isset($parts['port'])) {
            $url .= ':'.$parts['port'];
        }

        $url .= $parts['path'] ?? '';

        if (isset($parts['query'])) {
            $url .= '?'.$parts['query'];
        }

        if (isset($parts['fragment'])) {
            $url .= '#'.$parts['fragment'];
        }

        return $url;
    }

    /**
     * Keep only real Yupoo photo CDN URLs.
     */
    private function isAllowedImageUrl(string $url): bool
    {
        if (str_starts_with($url, '/storage/')) {
            return true;
        }

        $parts = parse_url($url);

        return isset($parts['scheme'], $parts['host'])
            && $parts['scheme'] === 'https'
            && $parts['host'] === 'photo.yupoo.com'
            && ! str_contains($url, '567')
            && ! str_contains($url, 'Restricted Access');
    }

    /**
     * Build a stable, unique product slug.
     */
    private function uniqueProductSlug(string $titulo, string $albumId): string
    {
        $slug = Str::slug($titulo) ?: 'album';

        return $slug.'-'.$albumId;
    }

    /**
     * Build a stable category slug.
     */
    private function uniqueCategorySlug(string $titulo): string
    {
        return (Str::slug($titulo) ?: 'categoria').'-'.substr(sha1($titulo), 0, 8);
    }

    /**
     * Build a Spanish title for display while keeping the source title in description.
     */
    private function spanishTitle(string $albumId, string $originalTitle): string
    {
        $cleanOriginal = trim($originalTitle);
        $club = $this->detectClub($cleanOriginal);
        $season = $this->detectSeason($cleanOriginal);

        $parts = ['Jersey retro'];

        if ($club !== null) {
            $parts[] = $club;
        }

        if ($season !== null) {
            $parts[] = $season;
        }

        return implode(' - ', $parts);
    }

    /**
     * Detect a club name from the original Yupoo title.
     */
    private function detectClub(string $title): ?string
    {
        $map = [
            'classic-football-shirts052' => 'Retro',
            '巴萨' => 'Barcelona',
            '皇马' => 'Real Madrid',
            '曼联' => 'Manchester United',
            '利物浦' => 'Liverpool',
            '阿森纳' => 'Arsenal',
            '切尔西' => 'Chelsea',
            '曼城' => 'Manchester City',
            '热刺' => 'Tottenham',
            '国米' => 'Inter',
            'AC' => 'AC Milan',
            'AC米兰' => 'AC Milan',
            '尤W' => 'Juventus',
            '尤文' => 'Juventus',
            '罗马' => 'Roma',
            '拉齐奥' => 'Lazio',
            '拜仁' => 'Bayern Munich',
            '多特' => 'Dortmund',
            '塞尔塔' => 'Celta Vigo',
            '瓦伦西亚' => 'Valencia',
            '巴西' => 'Brazil',
            '阿根廷' => 'Argentina',
            '葡萄牙' => 'Portugal',
            '西班牙' => 'Spain',
            '德国' => 'Germany',
            '法国' => 'France',
            '英格兰' => 'England',
            '荷兰' => 'Netherlands',
            '日本' => 'Japan',
            '墨西哥' => 'Mexico',
            '河床' => 'River Plate',
            '弗拉门戈' => 'Flamengo',
            '博塔弗戈' => 'Botafogo',
            '圣保罗' => 'Sao Paulo',
            '桑托斯' => 'Santos',
            '纽卡斯尔' => 'Newcastle United',
            '西汉姆' => 'West Ham',
            '阿贾克斯' => 'Ajax',
            '马竞' => 'Atletico Madrid',
            '皇马' => 'Real Madrid',
            '德里城' => 'Derry City',
            '凯尔特人' => 'Celtic',
            '流浪者' => 'Rangers',
            '巴西国家队' => 'Brazil',
            '阿根廷国家队' => 'Argentina',
            '日本国家队' => 'Japan',
            '英格兰国家队' => 'England',
            '葡萄牙国家队' => 'Portugal',
            '法国国家队' => 'France',
            '德国国家队' => 'Germany',
        ];

        foreach ($map as $needle => $club) {
            if (str_contains($title, $needle)) {
                return $club;
            }
        }

        return null;
    }

    /**
     * Detect a season/year from the original Yupoo title.
     */
    private function detectSeason(string $title): ?string
    {
        if (preg_match('/(19\d{2}\/\d{2}|20\d{2}\/\d{2}|19\d{2}|20\d{2})/', $title, $matches)) {
            return $matches[1];
        }

        return null;
    }

    private function recordLabel(array $record): string
    {
        return (string) ($record['titulo'] ?? $record['album_id'] ?? 'registro');
    }

    private function summaryText(array $summary): string
    {
        return sprintf(
            'Records: %d | Products created: %d | Products updated: %d | Categories: %d | Images: %d | Errors: %d',
            $summary['records'],
            $summary['products_created'],
            $summary['products_updated'],
            $summary['categories_created'],
            $summary['images_synced'],
            count($summary['errors'])
        );
    }
}
